### ISSUE TITLE
failing to run test script

### ISSUE THREAD

**Issue by tshepang** [ntls-io/ntc-smart-contract-mvp#18]
```
❯ python scripts/test_SmartContractDeployment.py
Traceback (most recent call last):
  File "/usr/lib/python3.11/urllib/request.py", line 1348, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/usr/lib/python3.11/http/client.py", line 1282, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.11/http/client.py", line 1328, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.11/http/client.py", line 1277, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.11/http/client.py", line 1037, in _send_output
    self.send(msg)
  File "/usr/lib/python3.11/http/client.py", line 975, in send
    self.connect()
  File "/usr/lib/python3.11/http/client.py", line 941, in connect
    self.sock = self._create_connection(
                ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/socket.py", line 851, in create_connection
    raise exceptions[0]
  File "/usr/lib/python3.11/socket.py", line 836, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

**Comment by tshepang** [comment]
hah, was because I did not start the sandbox (`./sandbox up`)

**Comment by yebaitou** [comment]
Hi, I also encountered this problem, I started the python sandbox, but it still didn't solve it, how did you do it

**Comment by tshepang** [comment]
`./sandbox` is a shell script that starts docker containers and other things... see (2) and (3) on the readme
